### ISSUE TITLE
latest release breaks on debian/apache/modwsgi

### ISSUE THREAD

**Issue by lordvlad** [ggasoftware/ketcher#1]
https://github.com/ggasoftware/ketcher/commit/d1356b7c643ed40390a8e90dada215cf13947d9a is the last commit that works fine on my machine. All versions after that return with "Indigo libraries are not found".

Im running Debian GNU/Linux 7.5 (wheezy), Apache 2.2.22, Python 2.7.5

I can do `import indigo` from the python REPL just fine. Any ideas what might be wrong? How can I help you debugging that?

**Comment by kolya-ay** [comment]
Sorry for the delay, we are migrating to the new infrastructure under [EPAM's wings](http://lifescience.opensource.epam.com/) so we missed your question. It seems that your issue is that python cannot find `indigo` dir in its `sys.path`. Do you able to run `PYTHONPATH=/path/to/indigo-libs python ketcher.py`? If the issue appears only in Apache-WSGI mode you could use the `python-path` option of the [WSGIDaemonProcess](https://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGIDaemonProcess) directive.

Here is example of Apache virtualhost configuration running Ketcher:

```
  <VirtualHost *:80>
      WSGIDaemonProcess ketcher python-path=/path/to/indigo-libs
      WSGIProcessGroup ketcher
      WSGIScriptAlias /example /path/to/ketcher/ketcher.py
      AliasMatch ^/example/(.+\.(js|css|html|ico|gif|jpg|png))$ /path/to/ketcher/$1
  </VirtualHost>
```

Herewith Ketcher will be available at `http://<yourip>/example/ketcher.html`. Hope this is still valuable for you;)

**Comment by lordvlad** [comment]
hey,

thanks for the reply. The issue has been resolved in the meantime, it was an outdated debian indigo package, which was missing the indigo-inchi part. My (ex-)collegues got it working by building indigo from the latest sources. I think the issue can be closed. Thanks.
